version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks: 
      - challenge-network
    ports: 
      - "8080:80"
    depends_on:
      - app
  
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    container_name: challenge-node
    command: bash -c "npm install && npm run start:dev"
    volumes:
      - ./node:/usr/app:z
      - /usr/app/node_modules
    ports:
      - "3333:3333"
    networks: 
      - challenge-network
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /data/application/table.sql
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes: 
      - .docker/mysql:/var/lib/mysql:z
      - .docker/data:/data/application:z
    environment: 
      - MYSQL_DATABASE=challenge02
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - challenge-network

networks: 
  challenge-network:
    driver: bridge   
   